version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-data-setup:/setup
    tty: true
    environment:
      - RABBITMQ_DEFAULT_USER=ifpb
      - RABBITMQ_DEFAULT_PASS=ifpb
      - CLUSTERED=true
      - RABBITMQ_ERLANG_COOKIE=default_key
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ifpb
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
      PGADMIN_DEFAULT_PASSWORD: ifpb
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    links:
      - postgres
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres-data:
  rabbitmq-data:
  rabbitmq-data-setup:
  pgadmin-data: